apiVersion: v1
kind: Service
metadata:
  name: {{ include "oc-console-ui.fullname" . }}
  labels:
    {{- include "oc-console-ui.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oc-console-ui.selectorLabels" . | nindent 4 }}
